### ISSUE TITLE
質問: 問2.1および問2.2がテキストとして閉じているか

### ISSUE THREAD

**Issue by 2222-42** [smlsharp/mlpractice-book#2]
SML# 入門者です。問2.1と問2.2に関して質問があります。

問2.1を解こうと試みていました。

`makePrintString`により得られた結果の文字列を、対話型モードで評価することが期待されていますが、その方法がわからず、そこで詰まってしまいました。

`OS.Process.system`で`smlsharp`を呼び出し、そこで実行させるのか、とも考えたのですが、評価する文字列を引数として渡すということも許容されていないようでした。そこで以下の質問に答えていただきますと幸いです。

`makePrintString`により得られた結果の文字列を、対話型モードで評価する、ということは、p.42までの内容を使って解くことは可能なのでしょうか？

ご回答いただければ幸いです。

**Comment by AtsushiOhori** [comment]
ご質問ありがとうございます。概ね、お書きになった
> OS.Process.systemでsmlsharpを呼び出し、そこで実行させる

の方針で実現できます。

例えば、Listストラクチャを例に考えてみましょう。達成したい効果は、
- smlsharpが対話型で、`structure List = List;`を評価して得られる出力結果を、ファイルResults/List.txtに書き出す

です。

この効果は、もちろん、Linuxシェルでキーボードから直接以下のように入力すれば、実現できます。

```
$ smlsharp > Results/List.txt
structure List = List;
^D
```

問2.1が求めているのは、この処理を実行するsmlsharpの関数を書くことです。その方針は以下の通りです。

1. シェルで実行すべき文字列を、makePrintString関数と文字列連結演算 ^
を使って組み立てる。組み立てるべき文字列は、問2.1の項目３で示した"cat文字列"
をファイルに書き出す文字列と似たような構造です。

2. OS.Procesws.system関数を組み立てた文字列に適用し、実行。
Listストラクチャに限定すれば、ステップ１と２は以下のように実行できます。
```sml
val S = 
    "smlsharp > Results/List.txt <<EOF\n"
  ^ makePrintString "List"
  ^ "\n"
  ^ "EOF\n"
val _ = OS.Process.system S
```
3. さらに、問では、以上のステップを、"List"などのストラクチャ名を引数とする関数
`execPrint`にまとめることを求めています。

**Comment by 2222-42** [comment]
AtsushiOhori さん

丁寧に解説いただきありがとうございます。

私の推測が誤っており、見当違いな方面で検討しつづけていたため、Ohoriさんのご提示いただきました解決策に至ることができませんでした。

こちらの方針ですと問2.1が求めている関数を書くことができそうです。

ありがとうございます。
